Neeham/Twitter-like-website

- README.md
> Added my github username

- README.md
> NodeBeast's First Branch

- .gitignore
- .htaccess
- README.md
- index.php
> tino's pull request

- README.md
I simply removed the last heading that was add by @TinoBalle (Just doing some test to get use to GitHub) 😄
> Removed last heading

- README.md
This is a test from Atom editor!
> Testing Pull request

- index.php
Tel que demande 
j ai enlever un "bla"
> Travailler sur page index

- Meeting Minutes/Meeting#1_jan20.txt
- User-Stories/User_story_front_end.txt
Includes a plan of action due for Jan 30th
> Updated meeting minutes for tutorial meeting 

- index.php
> Reverted the code

- assets/alert.php
- assets/logout.php
- assets/query.php
- pages/debug.php
- pages/login.php
- pages/navbar.php
- Implemented query for login/register. 
- Added code to handle/display error to username when wrong username/pass is entered or during the registration, the username already exists.
> Query: Login, Register

- index.php
Fixed: The user will not be prompt to log in if they are already logged in.
They will be redirected to feed page if they are already logged in.
> Fixed: Login page already logged in

- sounds/.travis.yml
> Travis Updated

- assets/query.php
- pages/profile.php
Attempted to implement function to display a logged in user's Quacks (not 100% functional yet)
> Issue #69 - Display A User's Previous Quacks

- css/custom.css
- js/feed.js
- pages/feed.php
- repeated/header.php
Added the front-end UI for the feed page which includes a text box with a character limit, an area to view the tweets of users you follow, an area with follower suggestions, placeholder buttons, and a simple script to add a new quack to the feed
> #22 Added the front-end UI for the feed page

- assets/debug.php
Not an important change but thought I'd do it :)
> Made changes to debug page to better visualize it :)

- index.php
- pages/profile.php
- pages/register.php
Fixed the format of the forms for the login, register and posting a tweet page.
> Changed format of the forms so it can fit the screen properly.

- assets/debug.php
- assets/query.php
- index.php
- pages/feed.php
- pages/profile.php
- pages/register.php
When the user press the *Quack button to post. The first thing we should do is grab the current system date and time then proceed with the rest of the steps. Afterward we can save into database the time we captured the click on the button along with the quack post.
> Changed query order.

- assets/alert.php
- assets/loggedin.php
- assets/query.php
- assets/verify.php
- index.php
- pages/register.php
- repeated/navbar.php
#48 - Development
When a user register an account, they will not be able to log in until they have verified their email.
Once the email has been verified, the user will be able to login.
> Email Verification

- index.php
- pages/profile.php
- pages/register.php
- repeated/header.php
Instead of repeating a portion of a code on multiple pages. It has been added into one file which will be included to all the files that are accessing it.
> Code refraction.

- css/custom.css
- pages/feed.php
- pages/profile.php
> Minor change

- assets/query.php
- assets/verify.php
- index.php
- pages/feed.php
- pages/profile.php
- pages/register.php
- repeated/header.php
- repeated/navbar.php
Removed some lines that were repeated or were no longer needed due to it's not being used.
> Code Refraction

- assets/query.php
- pages/feed.php
Just showing the username of the logged in session under the posted quack's.
> Quack's heading now display username

- assets/query.php
#42 #43 
Commented the query code on how we will implement the future code in order to accomodate the core feature that are required for this project.
> Commenting code for future references

- assets/alert.php
- assets/loggedin.php
- assets/query.php
- assets/verify.php
#103 
Enhanced the alerts that are displayed to user across the pages.
> Enhancement to alerts displayed

- css/custom.css
- index.php
- pages/feed.php
- pages/register.php
I have added a second box for the list of followers and have have changed the first box from "you may know" to following
> #83 modified boxes for following and followers list

- pages/feed.php
> Testing is done

- README.md
- assets/alert.php
- assets/loggedin.php
- assets/query.php
- assets/verify.php
- css/custom.css
- index.php
- pages/feed.php
- pages/profile.php
- repeated/header.php
- repeated/navbar.php
- repeated/searchUser.php
- repeated/test.php
#103 #83 #43 #22 
A lot has been changed, overall the architecture of the project has changed.
The URL will not read the parameter send to it. Based on that it will decide whether it should show the current session that's logged in their quack or the user they are following.
Alert has been enhanced
You can now search a user to see their profile and in the future, you can follow them
Name, Email, Follower Count, Following Count are now displayed on the user profile.
> #103 #83 #43 #22 Architecture of the overall project changed

- assets/alert.php
- assets/query.php
- pages/profile.php
- repeated/header.php
#114 #43 
Turns out, we had 2 different type of Jquery being included to the same file so it was being overwritten by the newer version. The function we were using is not recognized by newer version of JQuery. In order to solve this, the old version of JQuery is now included and the newer version has been removed.
Added query for follow and unfollowing a user
> #114 #43 Fixed Bug and Added Query for Follow/Unfollow

- js/profile.js
- pages/feed.php
- pages/profile.php
- repeated/header.php
- repeated/navbar.php
#103 and #43
I moved the Quackbox to the feed page. 
Turn the Logout link to a Logout button.
Create a Follow button in Profile section (under the user's name and picture). The follow button only appears when viewing others profiles and not the own profile.   
These modification was under Hassan's supervision.
> #103 #43 Oussama 

- assets/query.php
#83  #22 
When you view another user profile, you will see their full name rather than their first name.
Fixed alert and redirection of the page upon posting a quack.
> #83 #22 Profile now shows the full name of the user.

- assets/alert.php
- assets/query.php
- pages/feed.php
#22 #69 
Under feed, the logged in user will see their quack and the quack of the user they follow which will be ordered by latest to oldest tweet.
> #22 #69 Display Qaucks under Feed of user being followed

- assets/alert.php
- assets/query.php
- pages/feed.php
- pages/profile.php
#83 #114 
User can now view on their quack and the quack's of those who they follow under feed page.
Fixed issue related to Alert not showing under profile page.
> #83 #114 Fixed issue with Alert, Feed page now shows quacks

- pages/profile.php
#103 
Optimized code by making sure URL even make sense before running any html code
> #103 Checking url make sense with the DB query before outputing html code

- pages/profile.php
#43 Made the follow button disappear properly when looking at your own profile
> #43 Made the follow button disappear properly when looking at your own profile

- assets/query.php
- pages/profile.php
- pages/register.php
#43 
A user can chose to follow/unfollow a user by visiting their profile page.
> #43 Implemented the feature where a user can follow another user.

- assets/query.php
#42 
So far:
A logged in user can 'Like' or 'Unlike' a Quack that is being displayed on the feed.php page
Future:
Implement a counter for number of 'Likes' on a certain Quack
Attempt to 'Like' a Quack from another user that the logged in user is not following
> #42 - Implemented the 'Like' feature

- assets/alert.php
- assets/query.php
#42 
When a user likes a Quack they will be notified whether or not the post was successfully liked or not.
> #42 Updated Alert for liking a Quack.

- README.md
- assets/alert.php
- assets/query.php
#42 #124 
By hovering over the 'Like' button with your mouse, can see the number of users that liked a Quack
(This can be changed based on team's design)
A user can like a Quack from another user that they are not following.
Linked Travis CI current build status to README
> #42 #124 - Implemented like counter, fixed redirect issues, linked Travis CI build to README

- README.md
#103 
Previous pull request had a small bug in README
-copied build status into title of file
-did not copy Markdown version of build status
Travis CI build status should appear now
> #103 - Fix small error in README

- .gitignore
- assets/query.php
- js/feed.js
- js/profile.js
- pages/feed.php
- pages/profile.php
> #42 Implemented tippy.js for the like button tooltips

- assets/query.php
- css/custom.css
- js/profile.js
- pages/profile.php
- repeated/header.php
> #139 Changed the layout of the profile page to be more mobile friendly

- assets/query.php
#140 
The following was running the follower query while the follower query was running the following. Inverted the order in order to fix this issue.
> #140 Fixed the issue where the follower and following count query were inverted

- css/custom.css
- index.php
- pages/feed.php
- repeated/header.php
#139 Removed the "You may like" section on mobile, made the duck animation on the index page appear correctly on mobile screens, and removed the wave animation on mobile screens as it was not appearing correctly
> #139 Made changes so that the entire website is more mobile friendly

- js/feed.js
#103 Removed the javascript code to make a quack in the feed page. The code only made a quack on the client side only
> #103 Removed unneeded javascript code

- .htaccess
- assets/alert.php
- assets/query.php
- assets/verify.php
- index.php
- pages/feed.php
- pages/profile.php
- pages/register.php
- repeated/footer.php
- repeated/header.php
- repeated/navbar.php
#144 
The user has to enter their login info twice in order to login. 
Issue: When the user visited the website without www. in the url, and tried to login the session would be created based on non www. url but once the user is redirected to the login page, the url now contains www. and thus the user is forced to login again because the session does not exist. This time when the user logs in, they are able to continue its journey throughout the site.
The domain with www. and without www. were treating as 2 different domain (websites) by the session of the browser.
Solution: Modified .htaccess file to force the url to contain www. throughout the whole domain.
> #144 Fixed issue related to login.

- assets/query.php
#147 - Development
The problem occurred during the redirect portion (checks if the user is on their personal profile page or if a user is visiting another user's profile page).
Solved problem by adding 'exit' after every redirect statement
> #147 - Resolved 'Like' problem for profile page

- assets/alert.php
- assets/config.php
- assets/query.php
#154 
The modal will only be closed by either clicking the x icon or the close button. Clicking around the modal box will not close the modal any longer.
The size of the modal has also been reduced for better visual.
> #154 Fixed the issue where the modal would close by clicking outside of it.

- repeated/header.php
- repeated/navbar.php
- resources/js/adsbygoogle.js
- resources/js/checker.js
#164 
The website will display a message if adblock is detect and will display a message to the user.
Concept: When the website loads, a variable named adblock is set to true.
A javascript file named adsbygoogle.js is called right after in which the adblock variable is set to false.
When a user has an ad blocker, the adsbygoogle.js will not be executed since it will detect the word "ad"
Since the adblock variable has not changed to false, this implies that the website has an ad blocker and therefore a message should be displayed to the user regarding this.
> #164 Implemented code to detect whether an adblock is being used.

- assets/loggedin.php
- assets/query.php
- index.php
- repeated/navbar.php
#103 
Code refactoring and the database now stores the last time user logged on the website.
> #103 Code refactoring and last time user logged on the website.

- assets/query.php
- index.php
- pages/profile.php
- repeated/header.php
Removed code that were being used for debugging purposes.
> #103 Removed code that I added for debugging purposes.

- assets/loggedin.php
- index.php
#173 
Made changes to how sessions and cookies are handled. Saved a few lines of code and made the conditional statement follow a standard flow.
> #173 Made changes to how sessions and cookies are handled.

- assets/loggedin.php
- index.php
- repeated/header.php
- repeated/navbar.php
#103 repeated code across all pages have been added as part of the header since header is called in every pages.
> #103 Code Refactoring

- assets/query.php
> #102 Typo for email last logged in fixed. Changed email send format to html.

- repeated/header.php
- resources/css/custom.css
#102 Just changed the opacity of the register page.
> #102 Changed register page opacity.

- assets/alertsModals.php
- assets/config.php
- assets/debug.php
- assets/loggedin.php
- assets/logout.php
- assets/query.php
- assets/verify.php
- index.php
- pages/feed.php
- pages/profile.php
- pages/register.php
- repeated/footer.php
- repeated/header.php
- repeated/navbar.php
- resources/css/custom.css
- resources/js/custom.js
#103 Code refactoring and adding comments to lines of codes that looks complex.
> #103 Code Refactoring and adding comments.

- assets/query.php
- tests/DataObjects.php
#124 
- Updated the test cases' output for the Travis log
- Updated parameter passing in the query.php file for the test cases to check the inputs
> #124 - Updated the Follow, Register, and Search test cases

- assets/query.php
- pages/profile.php
- repeated/header.php
- resources/css/custom.css
- resources/js/custom.js
#164 #156 
Made sticky columns to scroll through individually. Efficient for advertisement display.
> #164 #156 Scrolling columns under feed and profile page.

- index.php
- pages/feed.php
- pages/profile.php
- pages/register.php
- repeated/footer.php
- repeated/header.php
- repeated/navbar.php
- resources/css/custom.css
#139 #103 
Website is more mobile friendly than ever. Code refactoring and css has been added.
> #139 #103 Made the site more mobile friendly and did code refactoring.

- assets/query.php
#124 
- Re implemented the input test for Register function (was deleted in the merge conflict)
> Issue #124 - Re implemented the input test for Register

- assets/emailSend.php
- assets/neeham_twitter.sql
- assets/query.php
- pages/feed.php
- pages/profile.php
#139 #103 
Made the site mobile friendly so it runs much more smoother than before.
Code refactoring for email send to the user upon registration.
> #103 #139 Code Refactoring

- repeated/navbar.php
Minor changes to text displayed upon AdBlocker detection.
> Changes to text displayed upon AdBlocker detection.

- README.md
> Updating readme with the additional features used.

- README.md
Forgot to add space between ## and Additional Features for readme file
> Heading typo for Additional Features

- README.md
Updated Debugger heading under Readme
> Updated Debugger heading under Readme

- README.md
> Updated Readme File.

- pages/feed.php
- repeated/header.php
- resources/css/custom.css
several changes in color, alignment, sizes
> (198) Uniforming newsfeed and profile page

- assets/query.php
- pages/register.php
Temporarily disabled the registration on Quack.
> Disabled registration button since random people are signing up on it :P

- resources/css/custom.css
#139 
Changes to CSS to make the website more mobile friendly across multiple devices.
> #139 Mobile Friendly for iPad

- assets/query.php
- pages/register.php
We had temporarily disabled registration on quack since we had unknown user signing up on it. The restriction has now been removed.
> Removed registration restriction.

- assets/query.php
- pages/profile.php
#139 changed the layout of profile page under mobile.
#157 Changed the upload button to make it look nicer.
> #139 #157 Changed profile upload button and mobile layout

- assets/query.php
#198 Changed the location of where the time of the quack was displayed
> #198 Brought the time at the bottom of the quack.

- .travis.yml
- tests/DataObjects.php
- tests/TestCases.php
#103 
- Removed old commented out code on travis.yml file
- Added descriptive comments to the TestCases and DataObjects files
> #103 - Code Refactor of Travis file and Test Files

- index.php
- repeated/header.php
- resources/css/custom.css
#198 Due to some error, my last push was not pushed on Github therefore I am pushing it again now.
> #198 Minor changes due to push error.
